### ISSUE TITLE
A slight typo in queue-empty-p

### ISSUE THREAD

**Issue by no-defun-allowed** [deadtrickster/safe-queue#1]
In [concurrency-lparallel.lisp](https://github.com/deadtrickster/safe-queue/blob/master/src/concurrency-lparallel.lisp#L30) there is a slight typo: `mailbox` in `(defun queue-empty-p (mailbox) ...)` should be `queue`, and the documentation should probably also be replaced similarly.

[My fork](https://github.com/nodefunallowed/safe-queue) fixes this, but I wrote an issue since I wasn't sure if people preferred to discuss pull requests first.

**Comment by no-defun-allowed** [comment]
@deadtrickster bump?

**Comment by deadtrickster** [comment]
Hey, please just open PR.

**Comment by no-defun-allowed** [comment]
Aight, will do.
